### ISSUE TITLE
[TASK:EPIC] Update to Apache Solr 8.8

### ISSUE THREAD

**Issue by dkd-friedrich** [TYPO3-Solr/ext-solr#2892]
We should update to the latest version of Apache Solr 8.8!

As things stand at present, the following steps are required:

- [ ] Update to Apache Solr 8.8
Apache Solr 8.8.1 is used in Dockerfile, Install script and Travis
- [ ] Consider fix in collapse feature
With Apache Solr 8.8.0 treatment of null and/or zero values is fixed, see [SOLR-15047](https://issues.apache.org/jira/browse/SOLR-15047). This issue exists since the variant feature was implemented, we have to adapt our integration tests to respect the new behavior of Solr.
- [ ] Adapt meta extract 
Tika 1.24 used since Apache Solr 8.6 behaves differently while extracting meta data, we have to adapt our `extractByQuery`, see 
[SOLR-14367](https://issues.apache.org/jira/browse/SOLR-14367)
