### ISSUE TITLE
[TASK:T12] Migrate Page indexing stack to TYPO3 12+ API

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3529]
### TYPO3 12+ blocked functionality:

- [x] [Core: Breaking: #96996 - Hook "checkEnableFields" removed](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96996-HookCheckEnableFieldsRemoved.html)
  To migrate:
  * `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['hook_checkEnableFields']`
- [x] [Core: Breaking: #97862 - Hooks related to generating page content removed](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97862-HooksRelatedToGeneratingPageContentRemoved.html) 
  To migrate:
  * `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-all']`
- [x] [Core: Breaking: #98303 - Removed hooks for language overlays in PageRepository](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98303-RemovedHooksForLanguageOverlaysInPageRepository.html)
  To migrate:
  * `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['getPageOverlay']`

### Without functionality since TYPO3 < 12

- [x] [Core: Breaking: #87193 - Deprecated functionality removed](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html)
  To remove: 
  * `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['tslib_fe-PostProc']`
  * `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['tslib_fe-PostProc']`
- [x] [Core: Breaking: #91473 - Deprecated functionality removed](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-91473-DeprecatedFunctionalityRemoved.html)
  To remove:
  * `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['isOutputting']`
