### ISSUE TITLE
[TASK] Use POST for Solr queries to be able to avoid enabled remote and body streaming

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3750]
**What should be done in the scope of this task?**

EXT:solr uses remote and body streams for delete queries. This should be avoided in future.
See: 
* https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html#security-2
* https://issues.apache.org/jira/browse/SOLR-14853

### Todos:

- [ ] Rewrite all queries using both features to POST
- [ ] Disable both features in Dockerfile 
- [ ] provide notes in the docs
- [ ] revert #3967 for 13+

Related: #3748 

### Target Version:

- [ ] 13 aka main, but only after branching release-12.0.x

**Comment by dkd-friedrich** [comment]
Done in #4073

Upcoming rebase of main Branch will include this adaptions for EXT:solr 13
