### ISSUE TITLE
[EPIC] Make EXT:solr TYPO3 13 LTS compatible

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3995]
# Infos and notes:

This task contains all the sub task to get EXT:solr woking within TYPO3 13 LTS:
**Note:** The compatibility to TYPO3 12 LTS MUST NOT be assured.

## Current state of TYPO3 13 LTS support

TYPO3 13 not yet supported. 

### Blocker for **Community Sprint 2024.05.16 + 17**
- [x] EPIC: Update PHPUnit + TYPO3 testing-framework on all repositories
  - [x] #3992
    - [x] #4024
  - [x] https://github.com/TYPO3-Solr/ext-tika/pull/223
  - [x] EXT:solrfal done in https://github.com/TYPO3-Solr/ext-solrfal/pull/277
  - [x] EXT:solrconsole done in https://github.com/TYPO3-Solr/ext-solrconsole/pull/81
  - [x] ~~EXT:solrdebugtools no PHPUnit https://github.com/TYPO3-Solr/ext-solrdebugtools~~
- [x] [TASK] Branch release-12.0.x from main
  - [x] [TASK] ext-solr release-12.0.x
  - [x] [TASK] solr-ddev-site release-12.0.x
  - [x] [TASK] ext-solrfal release-12.0.x
  - [x] [TASK] ext-tika release-12.0.x
  - [ ] ~~[TASK] ext-solrconsole release-12.0.x~~ (not relevant for codesprint)
  - [ ] ~~[TASK] ext-solrdebugtools release-12.0.x~~ (not relevant for codesprint)
- [x] [TASK] TYPO3 13 setup on main branch for:
  - [x] [TASK] ext-solr
  - [x] [TASK] solr-ddev-site
  - [x] [TASK] ext-solrfal
  - [x] [TASK] ext-tika
  - [ ] ~~[TASK] ext-solrconsole~~ (not relevant for codesprint)
  - [ ] ~~[TASK] ext-solrdebugtools~~ (not relevant for codesprint)

### Must have

- [x] #4038
- [x] #4041
- [x] #4058
- [x] [Access Plugin for Apache](https://github.com/TYPO3-Solr/solr-typo3-plugin)
  - [x] https://github.com/TYPO3-Solr/solr-typo3-plugin/issues/26
  - [x] https://github.com/TYPO3-Solr/solr-typo3-plugin/issues/29
- [x] #4165
- [x] #4161
   - `PageIndexerTest::canIndexPageWithAccessProtectedContentIntoSolr`
- [x] #4180
- [x] #4207
- [x] #4173
- [x] #4174
- [x] #4203
- [x] #4160
   - `ConnectionManagerTest::canFindSolrConnectionForMountedPageIfMountPointIsGiven`
   - `PageIndexerTest::canIndexMountedPage`
   - `PageIndexerTest::canIndexMultipleMountedPage`
- [x] #4208
- [x] #4185
  - [x] #4186
- [x] #4209
- [x] #4269
- [x] #4179 
  - [x] Adjusted
  - [ ] check the Docker artifacts for 13.0.x after release

### Nice to have

- [ ] #4103
- [ ] Rewrite SOLR_RELATION
- [ ] Event queue managing via TYPO3 backend
- [ ] Support for all monitoring types (delayed processing) in solrfal TYPO3-Solr/ext-solrfal/issues/245
- [ ] #4141
- [ ] #4076

### Deprecations

- [ ] [TASK] Remove deprecated queue.[indexConfig].table TypoScript setting

# Final 13.0.0

Scheduled for same or next week of TYPO3 13 LTS stable release.

- [x] #4271

# Current State:

## 2024.06.10

* Backend and indexing of all pages seemst to work properly.
* Frontend ans Search seems to work properly
* PhpStan issues fixed
* Unit tests still fail
* Integration tests still fail

## 2024.07.04

* Unit tests fixed
* Some integration tests still fail

## <a id="2024.09.17" />[2024.09.17]

The translated records and pages can be indexed now.

**Known issues**

* Some integration tests still fail
* Mount-Pages and `plugin.tx_solr.index.queue.[indexConfig].additionalPageIds` do not work
* Access restricted pages/records do not work
* BE-Modules sometimes produce the BE-Links with strange id parameter, which leads to exceptions.
   typo3/module/searchbackend/index-administration?id=0_1_500_501
   _Workaround: Chose desired page in tree again to get int UID again in address-bar_
   Most probably new issue and analyse is required.
   
## <a id="2024.09.30" />[2024.09.30]

The protected pages can be indexed now as well.
The BE-Modules work as expected again.

**Known issues**

* Indexing of cross-site mount pages and test coverage of mount pages indexing
* `plugin.tx_solr.index.queue.[indexConfig].additionalPageIds` does not work
